#define auto auto
#define abbruch break
#define falls case
#define zeichen char
#define konstant const
#define fortfahren continue
#define standard default
#define mache do
#define großedezimalzahl double
#define sonst else
#define aufzählung enum
#define extern extern
#define dezimalzahl float
#define für for
#define gehezu goto
#define wenn if
#define ganzzahl int
#define groß long
#define register register
#define rückgabe return
#define klein short
#define signiert signed
#define größe sizeof
#define statisch static
#define struktur struct
#define schaltung switch
#define definition typedef
#define vereinigung union
#define unsigniert unsigned
#define nichts void
#define veränderbar volatile
#define während while
#define haupt main
