/* stdio.h */

#define fehlerlöschen           clearerr
#define dschließen              fclose
#define dende                   feof
#define dspülen                 fflush
#define dholezeichen            fgetc
#define dholeposition           fgetpos
#define dholetext               fgets
#define döffnen                 dopen
#define ddruckf                 fprintf
#define dschreibezeichen        fputc
#define dschreibetext           fputs
#define dlese                   fread
#define dneuöffnen              freopen
#define dlesef                  fscanf
#define dsuchen                 fseek
#define dsetzeposition          fsetpos
#define dsagen                  ftell
#define dschreibe               fwrite
#define holezeichen             getc
#define holetext                gets
#define druckefehler            perror
#define druckeformat            printf
#define schreibezeichen         putchar
#define schreibetext            puts
#define lösche                  remove
#define spulezurück             rewind
#define leseformat              scanf
#define setzezwischenspeicher   setbuf
#define textdruckeformat        sprintf
#define textleseformat          sscanf
#define temporäredatei          tmpfile
#define temporärername          tmpnam
#define zeichenzurückgeben      ungetc